[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
staking_on_solana = "5Af8446iFooBfKv8KqTTqSwxRrZxEH7ZBzZqf2e1ohkM"

[programs.localnet]
staking_on_solana = "5Af8446iFooBfKv8KqTTqSwxRrZxEH7ZBzZqf2e1ohkM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/letho/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
