[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
staking_on_solana = "22VFe4wjjmrvUcz2JhzLnaepnu7y876qgh8ivWqmx7SU"

[programs.devnet]
staking_on_solana = "22VFe4wjjmrvUcz2JhzLnaepnu7y876qgh8ivWqmx7SU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet" # Localnet, devnet
wallet = "/home/letho/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
